# Generated by Django 4.2.16 on 2024-09-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(blank=True, max_length=50, verbose_name='ライン名')),
                ('period', models.CharField(blank=True, max_length=50, verbose_name='時間帯')),
                ('date', models.DateField(blank=True, verbose_name='製造日')),
                ('bin', models.IntegerField(blank=True, verbose_name='便')),
                ('order', models.IntegerField(blank=True, verbose_name='順番')),
                ('hinban', models.IntegerField(blank=True, verbose_name='品目コード')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='品目名称')),
                ('yosoku', models.IntegerField(blank=True, verbose_name='予測生産')),
                ('kubun', models.CharField(blank=True, max_length=10, verbose_name='処理区分名称')),
                ('value', models.FloatField(blank=True, verbose_name='指示量')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name='単位')),
                ('ctype', models.CharField(blank=True, max_length=10, verbose_name='調理種別')),
                ('batdeki', models.FloatField(blank=True, verbose_name='バッチ当り出来高')),
                ('battime', models.IntegerField(blank=True, verbose_name='バッチ当り調理時間')),
                ('hdeki', models.FloatField(blank=True, verbose_name='1時間当り出来高')),
                ('changey', models.IntegerField(default=0, verbose_name='切替予定')),
                ('processy', models.IntegerField(blank=True, verbose_name='作業時間')),
                ('starty', models.DateTimeField(blank=True, verbose_name='開始予定')),
                ('endy', models.DateTimeField(blank=True, verbose_name='終了予定')),
                ('startj', models.DateTimeField(blank=True, verbose_name='開始時刻')),
                ('shimej', models.DateTimeField(blank=True, verbose_name='締切時間')),
                ('endj', models.DateTimeField(blank=True, verbose_name='終了時刻')),
                ('changej', models.IntegerField(blank=True, verbose_name='切替時間')),
                ('processj', models.IntegerField(blank=True, verbose_name='作業時間')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
            ],
            options={
                'db_table': 'kouteikanri_chouriproc',
            },
        ),
    ]
