# Generated by Django 4.2.16 on 2024-10-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chourikoutei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='batdeki',
            field=models.FloatField(blank=True, null=True, verbose_name='バッチ当り出来高'),
        ),
        migrations.AlterField(
            model_name='process',
            name='battime',
            field=models.IntegerField(blank=True, null=True, verbose_name='バッチ当り調理時間'),
        ),
        migrations.AlterField(
            model_name='process',
            name='changej',
            field=models.IntegerField(blank=True, null=True, verbose_name='切替時間'),
        ),
        migrations.AlterField(
            model_name='process',
            name='ctype',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='調理種別'),
        ),
        migrations.AlterField(
            model_name='process',
            name='endj',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='process',
            name='endy',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了予定'),
        ),
        migrations.AlterField(
            model_name='process',
            name='hdeki',
            field=models.FloatField(blank=True, null=True, verbose_name='1時間当り出来高'),
        ),
        migrations.AlterField(
            model_name='process',
            name='hinban',
            field=models.IntegerField(blank=True, null=True, verbose_name='品目コード'),
        ),
        migrations.AlterField(
            model_name='process',
            name='kubun',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='処理区分名称'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='品目名称'),
        ),
        migrations.AlterField(
            model_name='process',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='順番'),
        ),
        migrations.AlterField(
            model_name='process',
            name='processj',
            field=models.IntegerField(blank=True, null=True, verbose_name='作業時間'),
        ),
        migrations.AlterField(
            model_name='process',
            name='processy',
            field=models.IntegerField(blank=True, null=True, verbose_name='作業時間'),
        ),
        migrations.AlterField(
            model_name='process',
            name='shimej',
            field=models.DateTimeField(blank=True, null=True, verbose_name='締切時間'),
        ),
        migrations.AlterField(
            model_name='process',
            name='startj',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始時刻'),
        ),
        migrations.AlterField(
            model_name='process',
            name='starty',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始予定'),
        ),
        migrations.AlterField(
            model_name='process',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='単位'),
        ),
        migrations.AlterField(
            model_name='process',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='指示量'),
        ),
        migrations.AlterField(
            model_name='process',
            name='yosoku',
            field=models.IntegerField(blank=True, null=True, verbose_name='予測生産'),
        ),
    ]
