# Generated by Django 4.2.16 on 2024-10-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chourikoutei', '0002_alter_process_batdeki_alter_process_battime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='batcount',
            field=models.IntegerField(default=1, verbose_name='回数'),
        ),
    ]
