# Generated by Django 3.1.3 on 2020-11-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(blank=True, max_length=50, verbose_name='ライン名')),
                ('period', models.CharField(blank=True, max_length=50, verbose_name='時間帯')),
                ('date', models.DateField(blank=True, verbose_name='製造日')),
                ('bin', models.IntegerField(blank=True, verbose_name='便')),
                ('hinban', models.IntegerField(blank=True, verbose_name='品番')),
                ('price', models.FloatField(blank=True, verbose_name='単価')),
                ('kubun', models.CharField(blank=True, max_length=10, verbose_name='区分')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='製品名')),
                ('seisanh', models.IntegerField(blank=True, verbose_name='生産数h')),
                ('value', models.IntegerField(blank=True, verbose_name='数量')),
                ('seisand', models.FloatField(blank=True, verbose_name='生産高')),
                ('conveyor', models.FloatField(blank=True, verbose_name='コンベア速度')),
                ('staff', models.IntegerField(blank=True, verbose_name='人員')),
                ('panmm', models.CharField(blank=True, max_length=50, verbose_name='パンミリ数')),
                ('slicev', models.IntegerField(blank=True, verbose_name='スライス枚数')),
                ('slicep', models.IntegerField(blank=True, verbose_name='スライス能力')),
                ('changey', models.IntegerField(blank=True, verbose_name='切替予定')),
                ('processy', models.IntegerField(blank=True, verbose_name='生産時間')),
                ('starty', models.DateTimeField(blank=True, verbose_name='開始予定')),
                ('endy', models.DateTimeField(blank=True, verbose_name='終了予定')),
                ('startj', models.DateTimeField(blank=True, verbose_name='開始時間')),
                ('endj', models.DateTimeField(blank=True, verbose_name='終了時間')),
                ('changej', models.IntegerField(blank=True, verbose_name='切替時間')),
                ('processj', models.IntegerField(blank=True, verbose_name='実際時間')),
                ('status', models.IntegerField(default=0, verbose_name='status')),
                ('set', models.IntegerField(default=0, verbose_name='set')),
                ('setj', models.DateTimeField(blank=True, verbose_name='準備時間')),
                ('fkey', models.CharField(blank=True, max_length=50, verbose_name='fkey')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='comment')),
            ],
        ),
        migrations.AlterModelTable(
            name='process',
            table='kouteikanri_process',
        ),
    ]
