# Generated by Django 3.2.15 on 2024-09-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kouteikanri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='changey',
            field=models.IntegerField(default=0, verbose_name='切替予定'),
        ),
        migrations.AlterField(
            model_name='process',
            name='fkey',
            field=models.IntegerField(blank=True, verbose_name='fkey'),
        ),
        migrations.AddField(
            model_name='process',
            name='jigyousyo',
            field=models.CharField(blank=True, default='盛岡', max_length=50, verbose_name='事業所'),
        ),
    ]
